- name: SonarCloud Scan
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: |
    sonar-scanner \
      -Dsonar.projectKey=57e4df46831c0543cbb5de93848f5c2dc08d9fe1 \  
      -Dsonar.organization=biscayn \  
      -Dsonar.host.url=https://sonarcloud.io